name: dbt (DuckDB)

on:
  push:
    paths:
      - "energy_dbt/**"
      - ".github/workflows/dbt.yml"
  pull_request:
    paths:
      - "energy_dbt/**"
      - ".github/workflows/dbt.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'energy_dbt/dbt_project.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dbt-duckdb
        run: |
          python -m pip install --upgrade pip
          # keep this close to your local plugin version
          pip install "dbt-duckdb==1.9.4"

      - name: Write dbt profiles.yml for CI
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          energy_dbt:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: energy_dbt/energy.duckdb
                threads: 4
          YAML

      # If the big OPSD seed isn't committed (it shouldn't be), create a tiny seed
      # with just the columns we actually use. This keeps CI lightweight.
      - name: Create tiny seed if missing
        run: |
          if [ ! -f energy_dbt/seeds/time_series_60min_singleindex.csv ]; then
            mkdir -p energy_dbt/seeds
            cat > energy_dbt/seeds/time_series_60min_singleindex.csv <<'CSV'
utc_timestamp,DE_load_actual_entsoe_transparency,DE_wind_generation_actual,DE_solar_generation_actual
2015-01-01 00:00:00,41151,8852,
2015-01-01 01:00:00,40135,9054,
2015-01-01 02:00:00,39106,9070,
2015-01-01 07:00:00,41133,10000,2145
2015-01-01 08:00:00,42963,10234,2516
2015-01-01 09:00:00,45088,11012,2600
CSV
          fi

      - name: dbt debug
        working-directory: energy_dbt
        run: dbt debug

      - name: dbt seed
        working-directory: energy_dbt
        run: dbt seed --full-refresh

      - name: dbt run
        working-directory: energy_dbt
        run: dbt run --full-refresh

      - name: dbt test
        working-directory: energy_dbt
        run: dbt test

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-target
          path: |
            energy_dbt/target
            energy_dbt/energy.duckdb
          if-no-files-found: ignore